#This generates 500 "identification values" that are 4-7 numbers (only) in length and outputs to a file
#The idea is to pair with the names from MakeApps.ps1 and create a list of application names and IDs that can be manipulated or input into a spreadsheet
#I feel like there's a better way to define the $ID variable but I wanted these scripts to be purely generated by AI and see if they'd fulfill their purpose (yes!)
#Combine with the MakeApps.ps1 and MakeMorePeople.ps1 to create a believable list of applications with names, IDs and support teams



Function Get-RandomID {
    param(
        [int]$Length
    )

    $ID = Get-Random -Minimum ([math]::Pow(10, $Length - 1)) -Maximum ([math]::Pow(10, $Length))
    return [int]$ID
}

$IDs = @()
while ($IDs.Count -lt 500) {
    $Length = Get-Random -Minimum 4 -Maximum 7
    $ID = Get-RandomID -Length $Length

    if (-not $IDs.Contains($ID)) {
        $IDs += $ID
    }
}

$OutputTable = $IDs | Sort-Object | Format-Table -AutoSize | Out-String

$OutputFilePath = "id_values.txt"
$OutputTable | Out-File -FilePath $OutputFilePath

Write-Host "Generated 500 unique whole number ID values. Saved to $OutputFilePath."
